# Generated by Django 3.2.9 on 2021-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFromDjango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exampleid', models.IntegerField()),
                ('otherattribute', models.TextField()),
            ],
        ),
    ]
