# Generated by Django 3.2.9 on 2021-12-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0004_medicalvault_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=300)),
                ('MedicalVaultName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smdproject.medicalvault')),
            ],
        ),
    ]
