# Generated by Django 3.2.9 on 2021-12-08 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0005_vaultowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaultowner',
            old_name='MedicalVaultName',
            new_name='vault_name',
        ),
    ]
