# Generated by Django 3.2.9 on 2021-12-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0006_rename_medicalvaultname_vaultowner_vault_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultowner',
            name='vault_name',
        ),
        migrations.AddField(
            model_name='medicalvault',
            name='vault_owner',
            field=models.ManyToManyField(blank=True, null=True, to='smdproject.VaultOwner'),
        ),
        migrations.AddField(
            model_name='vaultowner',
            name='email',
            field=models.EmailField(default='test', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
