# Generated by Django 3.2.9 on 2021-12-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0007_auto_20211208_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultowner',
            name='email',
        ),
    ]
