# Generated by Django 3.2.9 on 2021-12-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0008_remove_vaultowner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalvault',
            name='vault_owner',
        ),
    ]
