# Generated by Django 3.2.9 on 2021-12-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0009_remove_medicalvault_vault_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalvault',
            name='vault_owner',
            field=models.ManyToManyField(blank=True, null=True, to='smdproject.VaultOwner'),
        ),
        migrations.AddField(
            model_name='vaultowner',
            name='email',
            field=models.EmailField(default='default-email', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
