# Generated by Django 3.2.9 on 2021-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smdproject', '0012_auto_20211210_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment_hub',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_hub',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment_hub',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='experiment_hub',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
